export const queryKeys = {
  itemCategory: ['itemCategory'] as const,
  brandRecentSelected: ['brandRecentSelected'] as const,
  brandTop: ['brandTop'] as const,
  tempItem: ['tempItem'] as const,
  searchBrand: (brandName: string) => ['searchBrand', brandName] as const,
  hotPlace: ['hotPlace'] as const,
  recentPlace: ['recentPlace'] as const,
  interestCeleb: ['interestCeleb'] as const,
  hotCeleb: ['hotCeleb'] as const,
  recentCeleb: ['recentCeleb'] as const,
  searchCeleb: (celebName: string) => ['searchCeleb', celebName] as const,
  itemDetail: (itemId: number) => ['itemDetail', itemId] as const,
  searchHashtag: (name: string) => ['searchHashtag', name] as const,
  recentViewItem: ['recentViewItem'] as const,
  scrapItem: ['scrapItem'] as const,
  userUploadItem: ['userUploadItem'] as const,
  searchItem: (keyword: string) => ['searchItem', keyword] as const,
  questionDetail: (questionId: number) => ['questionDetail', questionId] as const,
  comment: (questionId: number) => ['comment', questionId] as const,
  recommendWait: (questionId: number) => ['recommendWait', questionId] as const,
  howAboutWait: (questionId: number) => ['howAboutWait', questionId] as const,
  findWait: (questionId: number) => ['findWait', questionId] as const,
  buyWait: (questionId: number) => ['buyWait', questionId] as const,
  buyNowItem: ['buyNowItem'] as const,
  curationItem: ['curationItem'] as const,
  howAboutItem: ['howAboutItem'] as const,
  luxuryItem: ['luxuryItem'] as const,
  newItem: ['newItem'] as const,
  efficientItem: ['efficientItem'] as const,
  hotCelebItem: (standard: string) => ['hotCelebItem', standard] as const,
  getHotSluver: (celebId?: number) => ['getHotSluver', celebId] as const,
}
